config:
  aws:region: us-east-1
  nsite-infra:accountId: "612153676415"
  nsite-infra:domain: global-network.nphunter.gg
  nsite-infra:zoneName: nphunter.gg
  nsite-infra:bucketName: nsite-global-network
  nsite-infra:githubOwner: illidan53
  nsite-infra:githubRepo: nsite
  nsite-infra:githubSubjectPrefix: repo:illidan53@11860868/nsite@1391590173
  nsite-infra:ownerIps:
    secure: AAABAHc9CbcgS9kuyNJOZo3luNCVbeiASk8gu9ZgHaGqWldfMBVRYAWBYLdx
  nsite-infra:ripeAtlasKey:
    secure: AAABAP1amFocQbC5MRl9ubDVNmRkJFiOUwBK4RNoXapqSmpguKafL65G4BtwUUzfr47b5S5sOvMZP1NvtKJwEtWoJFk=
